version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    entrypoint: sh -c "NODE_OPTIONS="--dns-result-order=ipv4first" npm install && npm run start:dev"
